name: Task - Build & Test

on:
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup build dependencies
        uses: "./.github/templates/setup-build"

      - name: Cache Build artefacts
        id: yarn-cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Run build
        run: yarn build
